### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/DomainRobert#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Bien hecho @Roberttovarv ... ¡Felicidades por este proyecto!
## Estilo de código y limpieza
- ¡Buen trabajo!
## Mejores prácticas/comentarios
- Muy bien resuelto y muy original

**Comment by Roberttovarv** [comment]
Gracias Edo!
